#
# On document changes and on demand: Deploy the dev documentatio
#
name: Deploy the dev documentation
on:
  workflow_dispatch: {}
  push:
    paths:
      - "docs/**"
      - mkdocs.yml
    branches:
      - main
jobs:
  deploy:
    name: Deploy the dev documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.12.3
      - name: Install dependencies
        run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material.git
          pip install mike
          pip install mkdocs-macros-plugin
        env:
          GH_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Deploy the dev documents
        run: mike deploy --push dev
