#
# Daily Test: Test latest libbpfgo
#
name: Libbpfgo Test
on:
  workflow_dispatch: {}
  schedule:
    # Daily At 03:00
    - cron: "0 3 * * *"
  workflow_call:
jobs:
  compile-tracker:
    name: Test Latest libbpfgo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
      - name: Compile Tracker
        run: |
          make test-upstream-libbpfgo
